# Generated by Django 4.2.7 on 2024-01-21 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=datetime.datetime(2024, 1, 21, 9, 0, 17, 682285, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
